Implement PDF Uplaod
Zeta611/easyword-translator pull request #2
Opened 2024-05-23 05:08 UTC by retato-snu

1. PDF to text
2. remove line break
3. translate text

Can upload multiple files & can download only after preprocessing(remove line break)

2024-05-23 14:10 UTC, Zeta611 requested changes

2024-05-23 14:10 UTC, Zeta611 commented on easyword_translator/pdf.py
> +import fitz  # PyMuPDF
pyproject.toml 파일에  dependency로 추가 후,
```sh
poetry export -f requirements.txt --output requirements.txt
```
로 requirements.txt로 업데이트해야 합니다!

2024-05-23 14:10 UTC, Zeta611 commented on easyword_translator/run.py
> +        uplaod_file_list_box = gr.File(label="Uploaded Files")
오타 있어요 `uplaod_...` -> `upload_...`

2024-05-23 15:56 UTC, retato-snu commented on easyword_translator/pdf.py
> +import fitz  # PyMuPDF
PyMuPDF가 requirements에 있어서 상관없을것같긴한데...

2024-05-23 16:11 UTC, retato-snu commented on easyword_translator/pdf.py
> +import fitz  # PyMuPDF
pymupdf로 바꿨어요

2024-05-23 16:14 UTC, retato-snu commented
> 1. PDF to text
> 2. remove line break
> 3. translate text
> 
> Can upload multiple files & can download only after preprocessing(remove line break)

2024-05-24 00:50 UTC, Zeta611 approved these changes

2024-05-24 00:51 UTC, Zeta611 commented
LGTM!

2024-05-24 00:52 UTC, merged